### ISSUE TITLE
Replace tools build scripts with apt repos

### ISSUE THREAD

**Issue by leandro-lucarella-sociomantic** [sociomantic-tsunami/cachalot#12]
After all projects deploy tags to bintray apt repositories, we should include those repositories and get the binaries from there instead of building, installing the same default version as before.

The plan for the final v2.0.0 is:

- [x] Merge https://github.com/sociomantic-tsunami/ebtree/pull/9 and reate tag `v6.0.socio7-rc2` to verify the package uploading really works
- [x] Spread this to all the other repos that should produce packages: 

  - [x] https://github.com/dlang/dmd/pull/6904
  - [x] https://github.com/sociomantic-tsunami/tangort/issues/13
  - [x] https://github.com/sociomantic-tsunami/dmd-transitional/issues/2
  - [x] https://github.com/sociomantic-tsunami/d1to2fix/issues/19

- [x] Add the current used versions also to the bintray repo

  - [x] dmd1 v1.080.0
  - [x] dmd-transitional 2.070.2.s11
  - [x] libtangort-dmd-dev v1.7.0
  - [x] libebtree6{-dbg,-dev} v6.0.socio6
  - [x] d1to2fix v0.9.0

- [x] Use the apt repos in cachalot instead of building stuff (https://github.com/sociomantic-tsunami/cachalot/pull/15)
- [x] Do a release candidate
- [x] Close this issue. Release Cachalot v2.0.0 final

**Comment by andreas-bok-sociomantic** [comment]
>  libdrizzle v5.6.3 (v5.5.4 too? as @andreas-bok-sociomantic )

No `v5.6.3` is fine, but we would need **libdrizzle-redux6**, i.e `v6.0.4 `.

**Comment by leandro-lucarella-sociomantic** [comment]
Woops, all the libdrizzle packages have a wrong architecture. See https://github.com/sociomantic-tsunami/libdrizzle-redux/pull/186

**Comment by leandro-lucarella-sociomantic** [comment]
Removing libdrizzle from the list of dependencies because is not really needed for the core stuff and it's complex to fully beaverize and upload packages, as it currently uses a lot of travis features, like the mysql server.

**Comment by leandro-lucarella-sociomantic** [comment]
@mihails-strasuns-sociomantic is there anything else that you want to include in v2 or should I tag a rc and the final after a few day?

**Comment by mihails-strasuns-sociomantic** [comment]
I haven't yet tried updating dmd-transitional to use several versions but AFAICS cachalot already provides everything needed.

**Comment by leandro-lucarella-sociomantic** [comment]
v2.0.0-rc1 tagged and available in docker hub.

**Comment by leandro-lucarella-sociomantic** [comment]
Let's see how it goes for repos using the `v2-test` image for a couple of days

**Comment by leandro-lucarella-sociomantic** [comment]
Mmm, there seems to be some issue with d1to2fix: https://travis-ci.org/sociomantic-tsunami/d1to2fix/jobs/244874798

```
   rdmd build/production/tmp/test-snippets
/home/travis/build/sociomantic-tsunami/d1to2fix/submodules/experimental_allocator/src/std/experimental/allocator/package.d(322): Error: std.experimental.allocator.common.Ternary at /home/travis/build/sociomantic-tsunami/d1to2fix/submodules/experimental_allocator/src/std/experimental/allocator/common.d(14) conflicts with std.typecons.Ternary at /usr/include/dmd/phobos/std/typecons.d(7658)
/home/travis/build/sociomantic-tsunami/d1to2fix/submodules/experimental_allocator/src/std/experimental/allocator/package.d(328): Error: std.experimental.allocator.common.Ternary at /home/travis/build/sociomantic-tsunami/d1to2fix/submodules/experimental_allocator/src/std/experimental/allocator/common.d(14) conflicts with std.typecons.Ternary at /usr/include/dmd/phobos/std/typecons.d(7658)
/home/travis/build/sociomantic-tsunami/d1to2fix/submodules/experimental_allocator/src/std/experimental/allocator/package.d(348): Error: std.experimental.allocator.common.Ternary at /home/travis/build/sociomantic-tsunami/d1to2fix/submodules/experimental_allocator/src/std/experimental/allocator/common.d(14) conflicts with std.typecons.Ternary at /usr/include/dmd/phobos/std/typecons.d(7658)
```

Any ideas @mihails-strasuns-sociomantic ?

**Comment by mihails-strasuns-sociomantic** [comment]
Usual dmd version issue? You must pin upstream versions exacttly for each project, this shit breaks every single release.

**Comment by leandro-lucarella-sociomantic** [comment]
What do you mean? The previous build worked: https://travis-ci.org/sociomantic-tsunami/d1to2fix/builds/244875374. It was [built with cachalot xenial-v2.0.0-alpha1](https://travis-ci.org/sociomantic-tsunami/d1to2fix/jobs/244875376#L140) (170601e0545c, only checking xenial but it should be the same with trusty). These images shipped dmd 2.070.2-0 and dmd-transitional v2.070.2 according to the image metadata:
```
                "com.sociomantic.version.dmd": "2.070.2-0",
                "com.sociomantic.version.dmd-transitional": "v2.070.2",
```

The build that fails is using cachalot v2.0.0.-rc1 (5dc141d9d51a), which ships the same dmd and dmd-transitional versions (supposedly, now are specified in a more relaxed fashion, but they should be the same:
```
                "com.sociomantic.version.dmd": "2.070.x",
                "com.sociomantic.version.dmd-transitional": "2.070.x",
```

Let's check what is it really fetching...

OK, it seems like the dmd-bin package version is not pinned anymore: https://travis-ci.org/sociomantic-tsunami/cachalot/jobs/246221804#L2585, it was in the alpha1 release: https://travis-ci.org/sociomantic-tsunami/cachalot/jobs/241247039#L1850

I guess it got lost with all the changes on how to pick up the version...

**Comment by leandro-lucarella-sociomantic** [comment]
OK, here is the problem: https://travis-ci.org/sociomantic-tsunami/cachalot/jobs/246221804#L1748

I'll investigate.

**Comment by leandro-lucarella-sociomantic** [comment]
OK, it seems like the issue was a missing `apt-get update`... #17.

**Comment by leandro-lucarella-sociomantic** [comment]
d1to2fix now passed! :tada:

**Comment by leandro-lucarella-sociomantic** [comment]
OK, all projects using `v2-test` are now green using the latest `-rc2` (and the ones that are not building the image from scratch build much faster now, tangort went from 5m to 1m :D).

I'll release v2.0.0 final, let's hope we don't find more critical bugs :)
