### ISSUE TITLE
Cachalot builds broken due to git v2.13.x

### ISSUE THREAD

**Issue by nemanja-boric-sociomantic** [sociomantic-tsunami/cachalot#21]
Cachalot uses git 2.13.x for its images:

https://github.com/sociomantic-tsunami/cachalot/blob/v3.x.x/base.Dockerfile#L9
https://github.com/sociomantic-tsunami/cachalot/blob/v2.x.x/base.Dockerfile#L9

and it's using git's ppa: https://github.com/sociomantic-tsunami/cachalot/blob/7d2bfdb960d468977fd7b53694f6f716bc104b02/docker/base#L40

But since release of git v2.14.x, ppa doesn't host v2.13.x packages anymore, so the build is broken.
We should probably move to the more legacy git versions.

**Comment by leandro-lucarella-sociomantic** [comment]
I think we should probably switch back to not use the PPA, I don't think we need fancy new git features in CI builds.

**Comment by leandro-lucarella-sociomantic** [comment]
This would probably mean *downgrading* git in a new version, but...
