### ISSUE TITLE
Update dmd in docker Image

### ISSUE THREAD

**Issue by stefan-koch-sociomantic** [sociomantic-tsunami/cachalot#43]
Currently dmd is on `2.070.2` which is at this point over one year old,
We should update to the latest release which ocean can use. (`2.077`) at this point.
@leandro-lucarella-sociomantic, @mihails-strasuns-sociomantic

**Comment by nemanja-boric-sociomantic** [comment]
I feel we should be very careful with changes like this that potentially affects all our environment.

Note that the dmd installed in the `sociomantictsunami/dlang` image is not upstream `dmd`, but the `dmd-transitional` package provided by us. We have also `dmd-transitional=v2.071.*` version available, but at this point not all libraries are ready to support it in all versions (for example, swarm in version `v4.x.x` doesn't support it, and also ocean in `v3.x.x` doesn't support the `v2.077`).

Next, this step should/could be done only in the next major release of the cachalot images, and it should probably be the next stable compiler version (probably `v2.071`)

And last, the projects are already advised to specify their own supported versions of the DMD and to install it through the travis matrix, like here: https://github.com/sociomantic-tsunami/swarm/blob/v4.x.x/.travis.yml#L22-L25 (which also brings the patch version to the most up to date).

**Comment by leandro-lucarella-sociomantic** [comment]
> is not upstream `dmd`

We install `dmd` too in the image. This is only about `dmd`.

**Comment by nemanja-boric-sociomantic** [comment]
My bad, but most of the points should still stand (except we can move to `v2.077`, when we bump `dmd-transitional` to `v2.071`).

**Comment by leandro-lucarella-sociomantic** [comment]
I don't know if I understand correctly, you say we can only move to v2.077 if we move to transitional v2.071 too?

**Comment by nemanja-boric-sociomantic** [comment]
No, I don't mean unconditionally. I just think that the time when we can bump both compilers is at `v4.0.0`, right?

**Comment by leandro-lucarella-sociomantic** [comment]
Yes, definitely bumping default versions should only happen in majors.

**Comment by mihails-strasuns-sociomantic** [comment]
Bump of `dmd` version is not tied to ocean majors in any way because no ocean-using application currently is built/tested with upstream `dmd`.

**Comment by mathias-lang-sociomantic** [comment]
I too, would like `dmd-compiler=2.077.1-0.1`

**Comment by leandro-lucarella-sociomantic** [comment]
I'll probably release v4 once tangort v1.8.0 final is out (so it's installed by default in v4), for which I need people testing the rc.

**Comment by nemanja-boric-sociomantic** [comment]
I've tested the 1.8-rc in the DLS node for quite some time and I haven't had any issues.

**Comment by leandro-lucarella-sociomantic** [comment]
tangort 1.8.0 released. Cachalot v3.1.0 released. What else should we do for cachalot v4? Bumping DMD, anything else? I guess we are not ready for dmd-transitional v2.071.x, right @mihails-strasuns-sociomantic  ?

**Comment by mihails-strasuns-sociomantic** [comment]
Nope, not touching dmd-transitional yet.

As @mathias-lang-sociomantic mention above, we should bring upstream dmd to the same version it was in private dlang image (2.074 afair), but could also go straight for 2.077

**Comment by mathias-lang-sociomantic** [comment]
I think it would make a lot of sense to go straight for the upstream version which can compile our code.
