### ISSUE TITLE
add a init system to runtimebase image

### ISSUE THREAD

**Issue by camilo-schoeningh-sociomantic** [sociomantic-tsunami/cachalot#66]
Like dump-init:
https://github.com/Yelp/dumb-init

As we want to make sure that :
- application are getting PID1
- bash can be used from command line.

**Comment by mihails-strasuns** [comment]
Note: as this will be a major change in image semantics, this should be done against v7.x.x base branch (next major)

**Comment by camilo-schoeningh-sociomantic** [comment]
As I was considering to use kralli/tini as an alternative, I will stick to dumb-init. The reason for this is that dumb-init supports `Signal rewriting` which is a useful feature for kubernetes as kubernetes only supports SIGTERM.

**Comment by mihails-strasuns** [comment]
btw small remark regarding this:

> application are getting PID1

When init system is used, app won't be getting PID 1, it will be init process. Which, in its turn, will propagate signals properly and handle zombies (allowing to implement app almost the same as it would be on regular linux)
