### ISSUE TITLE
Move to normal SemVer branch names

### ISSUE THREAD

**Issue by leandro-lucarella-sociomantic** [sociomantic-tsunami/cachalot#7]
Even when unnecessary (as this repo will only have "Major and Patch releases" because we consider any changes to images, that are not really a "bug fix", risky enough to not move users automatically to them), it's weird to have a different branch scheme than we normally use.

So v1 will be renamed v1.x.x and v2, v2.x.x. There will be no v1.0.x branch for the reasons above, and all releases will be vX.0.Z.

**Comment by leandro-lucarella-sociomantic** [comment]
If I don't hear complains from you soon I will do the switch.

**Comment by mihails-strasuns-sociomantic** [comment]
What do version names in cachalot denote in latest scheme of things?

**Comment by leandro-lucarella-sociomantic** [comment]
You mean patch-level versions? I can see allowing updating software only to newer patch-level versions for example. Or other minor cosmetic things. There will be not patchlevel tags in docker though. My idea is to keep `v2.0.0` -> `img:v2-trusty` for example, but then `v2.0.1` will also be tagged `img:v2-trusty` in docker. I think is good to be able to provide transparent fixes without users having to point to a newer tag.

**Comment by mihails-strasuns-sociomantic** [comment]
No, major versions. Will they include specific installed package versions or just fetch bintray cache so that specific repos can install required versions manually?

**Comment by leandro-lucarella-sociomantic** [comment]
Major versions will ship a different set of pre-installed tools. Other versions will be always available as long as they are available in the respective apt repos.

So, if the default `dmd1` changes from v1.80.0 to v1.80.1 in cachalot `v2` (let's say is `v2.0.0`) then the new image will be v2.0.1 and the docker tag `v2` will be overwritten with `v2.0.1`.

If the default `dmd1` changes from v1.80.1 to v1.81.0 in cachalot `v2` (let's say is `v2.0.1`) then the new image will be `v3.0.0` and the docker tag `v3` will be created (pointing to `v3.0.0`).

**Comment by leandro-lucarella-sociomantic** [comment]
Any other comments / concerns about moving this way?

**Comment by mihails-strasuns-sociomantic** [comment]
Nothing from me, I think I more or less understand the plan now :)

**Comment by leandro-lucarella-sociomantic** [comment]
Done. Now also the default branch is v2.x.x as it's very unlikely that v1.x.x is touched again.
